#!/usr/bin/env python3
"""
Simple CGI test script for webserv
"""

print("Content-Type: text/html")
print()
print("<html>")
print("<head><title>CGI Test - Python</title></head>")
print("<body>")
print("<h1>Python CGI Script Works!</h1>")
print("<p>This response was generated by a Python CGI script.</p>")
print("</body>")
print("</html>")
